export enum KpcPseudoinstructionType {
    AddwI = "Add word immediate",
    Jl = "Jump label",
    Jasl = "Jump and save label",
    Jzfl = "Jump zero flag label",
    Jwnotzl = "Jump word not zero label",
    SetwI = "Set word immediate",
    Jnfl = "Jump negative flag label",
    Jcfl = "Jump carry flag label",
    LbromI = "Load byte rom immediate (address is immediate)",
    LbromoI = "Load byte rom offset immediate (offset is immediate)",
    LwromI = "Load word rom immediate (address is immediate)",
    LwromoI = "Load word rom offset immediate (offset is immediate)",
    LbramI = "Load byte ram immediate (address is immediate)",
    LbramoI = "Load byte ram offset immediate (offset is immediate)",
    LwramI = "Load word ram immediate (address is immediate)",
    LwramoI = "Load word ram offset immediate (offset is immediate)",
    LbextI = "Load byte external device immediate (address is immediate)",

    SbramI = "Store byte ram immediate (address is immediate)",
    SbramoI = "Store byte ram offset immediate (offset is immediate)",
    SwramI = "Store word ram immediate (address is immediate)",
    SwramoI = "Store word ram offset immediate (offset is immediate)",
    SbextI = "Store byte external device immediate (address is immediate)",

    Notw = "NOT word",
    OrI = "OR immediate",
    Orw = "OR word",
    OrwI = "OR word immediate",
    AndI = "AND immediate",
    Andw = "AND word",
    AndwI = "AND word immediate",
    XorI = "XOR immediate",
    Xorw = "XOR word",
    XorwI = "XOR word immediate",

    Getl = "Get label (get the most recent address of ROM instruction under given label)",

    Jwzl = "Jump word zero label",
    Jwnl = "Jump word negative label",
    Jwnotnl = "Jump word not negative label",
    Jofl = "Jump overflow flag label",
}